remote_theme: ddc-java/ddc-day
repository_links:
  enabled: true
page_navigator:
  enabled: true
titles_from_headings:
  enabled: true

title: Codebreaker
description: "An Android implementation of Bulls & Cows (aka Mastermind)"
author:
  name: Dagoberto Garcia
  copyright: false